meta_product_name: "Fétiche"
meta_title: "Fétiche.io : le site de rencontre pour toutes vos envies"
meta_description: "Pour des rencontres plus justes et avec des personnes qui vous correspondent."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
